/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendalibros.vista;

import tiendalibros.controlador.ControlAltaCliente;
import tiendalibros.controlador.ControlBorrarPedido;
import tiendalibros.controlador.ControlHacerPedido;


/**
 *
 * @author JoseR
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonHacerPedido = new javax.swing.JButton();
        botonBorrarPedido = new javax.swing.JButton();
        botonAltaCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        botonHacerPedido.setText("Hacer Pedido");
        botonHacerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHacerPedidoActionPerformed(evt);
            }
        });

        botonBorrarPedido.setText("Borrar Pedido");
        botonBorrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarPedidoActionPerformed(evt);
            }
        });

        botonAltaCliente.setText("Dar de alta nuevo cliente");
        botonAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBorrarPedido)
                    .addComponent(botonHacerPedido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(botonAltaCliente)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(botonHacerPedido)
                .addGap(46, 46, 46)
                .addComponent(botonBorrarPedido)
                .addGap(35, 35, 35)
                .addComponent(botonAltaCliente)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables para patrón MVC
        //Pedido pedido = new Pedido();
        VistaBorrarPedido vistaBorrarPedido;
        ControlBorrarPedido controlBorrarPedido;
        VistaHacerPedido vistaHacerPedido;
        ControlHacerPedido controlHacerPedido;      
        VistaAltaCliente vistaAltaCliente;
        ControlAltaCliente controlAltaCliente;
        
        

    private void botonBorrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarPedidoActionPerformed
        vistaBorrarPedido = new VistaBorrarPedido();
        controlBorrarPedido = new ControlBorrarPedido(vistaBorrarPedido);
        
        vistaBorrarPedido.asignarControlador(controlBorrarPedido);
        vistaBorrarPedido.arranca();       
    }//GEN-LAST:event_botonBorrarPedidoActionPerformed

    private void botonAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltaClienteActionPerformed
         vistaAltaCliente = new VistaAltaCliente();
         controlAltaCliente = new ControlAltaCliente(vistaAltaCliente);
         
         vistaAltaCliente.asignarControlador(controlAltaCliente);
         vistaAltaCliente.arranca();
         
    }//GEN-LAST:event_botonAltaClienteActionPerformed

    private void botonHacerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHacerPedidoActionPerformed
        vistaHacerPedido = new VistaHacerPedido();
        controlHacerPedido = new ControlHacerPedido(vistaHacerPedido);      
        vistaHacerPedido.asignarControlador(controlHacerPedido);
        vistaHacerPedido.arranca();   
    }//GEN-LAST:event_botonHacerPedidoActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAltaCliente;
    private javax.swing.JButton botonBorrarPedido;
    private javax.swing.JButton botonHacerPedido;
    // End of variables declaration//GEN-END:variables

    
    
    public void ocultarAltaCliente(){
    botonAltaCliente.setVisible(false);
    }
    
}
