/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendalibros.vista;

import javax.swing.JTextField;
import tiendalibros.controlador.ControlBorrarPedido;


/**
 *
 * @author JoseR
 */
public class VistaBorrarPedido extends javax.swing.JFrame {

    /**
     * Creates new form BorrarPedido
     */
    public VistaBorrarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCodigoPedido = new javax.swing.JLabel();
        textoCodigoPedido = new javax.swing.JTextField();
        botonRealizarBorrado = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCodigoPedido.setText("Codigo pedido");

        textoCodigoPedido.setColumns(10);

        botonRealizarBorrado.setText("Realizar borrado");
        botonRealizarBorrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarBorradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRealizarBorrado)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(labelCodigoPedido)
                        .addGap(43, 43, 43)
                        .addComponent(textoCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(labelResultado)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigoPedido)
                    .addComponent(textoCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonRealizarBorrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(labelResultado)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRealizarBorradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarBorradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRealizarBorradoActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRealizarBorrado;
    private javax.swing.JLabel labelCodigoPedido;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JTextField textoCodigoPedido;
    // End of variables declaration//GEN-END:variables


public String leerCodigoPedido (){
    return textoCodigoPedido.getText();
}

public void escribirResultado (String resultado){
    labelResultado.setText(resultado);
}
    
void asignarControlador (ControlBorrarPedido c) {
    
botonRealizarBorrado.addActionListener(c);
    
}

void arranca () {
    setVisible(true);

}
        

}
