/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendalibros.vista;

import javax.swing.JTextField;
import tiendalibros.controlador.ControlHacerPedido;
import tiendalibros.modelo.Pedido;

/**
 *
 * @author JoseR
 */
public class VistaHacerPedido extends javax.swing.JFrame {

    /**
     * Creates new form HacerPedido
     */
    public VistaHacerPedido() {
        initComponents();
    }

    void asignarControlador(ControlHacerPedido c) {

        botonRecuperarPedido.addActionListener(c);
        botonRecuperarPedido.setActionCommand("Recuperar pedido");

        botonGuardar.addActionListener(c);
        botonGuardar.setActionCommand("Guardar");

        botonGenerarFactura.addActionListener(c);
        botonGenerarFactura.setActionCommand("Generar factura");

        botonGenerarOrdenImprenta.addActionListener(c);
        botonGenerarOrdenImprenta.setActionCommand("Generar orden imprenta");

    }

    void arranca() {
        setVisible(true);

    }

    public String leerCodigoPedido() {
        return textoCodigoPedido.getText();
    }

    public String leerFechaPedido() {
        return textoFechaPedido.getText();
    }

    public String leerDNICliente() {
        return textoDNICliente.getText();
    }

    public void escribirFechaPedido(String fecha) {
        textoFechaPedido.setText(fecha);
    }

    public void escribirDNI(String dni) {
        textoDNICliente.setText(dni);
    }

    public void escribirLineaDePedido(String isbnLibro, int ejemplares){
        // Se escriebe una lína de pedido en la tabla
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        labelCodigoPedido = new javax.swing.JLabel();
        labelFechaPedido = new javax.swing.JLabel();
        textoCodigoPedido = new javax.swing.JTextField();
        textoFechaPedido = new javax.swing.JTextField();
        labelDNICliente = new javax.swing.JLabel();
        textoDNICliente = new javax.swing.JTextField();
        botonGenerarFactura = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonGenerarOrdenImprenta = new javax.swing.JButton();
        panel = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        botonGuardar = new javax.swing.JButton();
        botonRecuperarPedido = new javax.swing.JButton();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCodigoPedido.setText("Codigo pedido");

        labelFechaPedido.setText("Fecha pedido");

        labelDNICliente.setText("DNI cliente");

        botonGenerarFactura.setText("Generar factura");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonGenerarOrdenImprenta.setText("Generar orden imprenta");

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        panel.setViewportView(tablaLibros);

        botonGuardar.setText("Guardar");

        botonRecuperarPedido.setText("Recuperar pedido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCodigoPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFechaPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(432, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonGuardar)
                        .addGap(28, 28, 28)
                        .addComponent(botonGenerarFactura)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(botonGenerarOrdenImprenta))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addComponent(labelDNICliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoDNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(botonRecuperarPedido)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigoPedido)
                    .addComponent(textoCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDNICliente)
                    .addComponent(textoDNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaPedido)
                    .addComponent(textoFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonGenerarFactura)
                            .addComponent(botonCancelar)
                            .addComponent(botonGenerarOrdenImprenta)
                            .addComponent(botonGuardar)))
                    .addComponent(botonRecuperarPedido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        VistaMenuPrincipal vistaMenuPrincipal = new VistaMenuPrincipal();
        this.setVisible(false);
        vistaMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_botonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGenerarFactura;
    private javax.swing.JButton botonGenerarOrdenImprenta;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonRecuperarPedido;

    private javax.swing.JScrollPane panel;
    private javax.swing.JLabel labelCodigoPedido;
    private javax.swing.JLabel labelDNICliente;
    private javax.swing.JLabel labelFechaPedido;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JTextField textoCodigoPedido;
    private javax.swing.JTextField textoDNICliente;
    private javax.swing.JTextField textoFechaPedido;
    // End of variables declaration//GEN-END:variables


}
